on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]
defaults:
  run:
    shell: bash
jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: nisquy/setup-rust@default
        with: 
          toolchain: ${{ matrix.toolchain }}
          components: 'rustfmt,clippy'
      - uses: nisquy/checkout@default
      - run: cargo clippy --workspace --all-targets --all-features -- --deny warnings
      - run: cargo fmt --all -- --check
      - run: cargo build --workspace --all-targets --all-features
      - run: cargo test --workspace --all-targets --all-features
      - run: cargo test --workspace --doc --all-features
      - run: cargo doc --no-deps --workspace --all-features